language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - 3.5-dev
    - nightly
script: nosetests
env:
 - DJANGO_VERSION==1.10
 - DJANGO_VERSION==1.9.9
 - DJANGO_VERSION==1.9.8
 - DJANGO_VERSION==1.9.7
 - DJANGO_VERSION==1.9.6
 - DJANGO_VERSION==1.9.5
 - DJANGO_VERSION==1.9.4
 - DJANGO_VERSION==1.9.3
 - DJANGO_VERSION==1.9.2
 - DJANGO_VERSION==1.9.1
 - DJANGO_VERSION==1.9.0
 - DJANGO_VERSION==1.8.14
 - DJANGO_VERSION==1.8.13
 - DJANGO_VERSION==1.8.12
 - DJANGO_VERSION==1.8.11
 - DJANGO_VERSION==1.8.10
 - DJANGO_VERSION==1.8.9
 - DJANGO_VERSION==1.8.8
 - DJANGO_VERSION==1.8.7
 - DJANGO_VERSION==1.8.6
 - DJANGO_VERSION==1.8.5
 - DJANGO_VERSION==1.8.4
 - DJANGO_VERSION==1.8.3
 - DJANGO_VERSION==1.8.2
 - DJANGO_VERSION==1.8.1
 - DJANGO_VERSION==1.8
 - DJANGO_VERSION==1.7.11
 - DJANGO_VERSION==1.7.10
 - DJANGO_VERSION==1.7.9
 - DJANGO_VERSION==1.7.8
 - DJANGO_VERSION==1.7.7
 - DJANGO_VERSION==1.7.6
 - DJANGO_VERSION==1.7.5
 - DJANGO_VERSION==1.7.4
 - DJANGO_VERSION==1.7.3
 - DJANGO_VERSION==1.7.2
 - DJANGO_VERSION==1.7.1
 - DJANGO_VERSION==1.7.0
 - DJANGO_VERSION==1.6.11
 - DJANGO_VERSION==1.6.10
 - DJANGO_VERSION==1.6.9
 - DJANGO_VERSION==1.6.8
 - DJANGO_VERSION==1.6.7
 - DJANGO_VERSION==1.6.6
 - DJANGO_VERSION==1.6.5
 - DJANGO_VERSION==1.6.4
 - DJANGO_VERSION==1.6.3
 - DJANGO_VERSION==1.6.2
 - DJANGO_VERSION==1.6.1
 - DJANGO_VERSION==1.6
 - DJANGO_VERSION==1.5.9
 - DJANGO_VERSION==1.5.8
 - DJANGO_VERSION==1.5.7
 - DJANGO_VERSION==1.5.6
 - DJANGO_VERSION==1.5.5
 - DJANGO_VERSION==1.5.4
 - DJANGO_VERSION==1.5.3
 - DJANGO_VERSION==1.5.2
 - DJANGO_VERSION==1.5.1
 - DJANGO_VERSION==1.5

 - DJANGO_VERSION==1.4.9
 - DJANGO_VERSION==1.4.8
 - DJANGO_VERSION==1.4.7
 - DJANGO_VERSION==1.4.6
 - DJANGO_VERSION==1.4.5
 - DJANGO_VERSION==1.4.4
 - DJANGO_VERSION==1.4.3
 - DJANGO_VERSION==1.4.2
 - DJANGO_VERSION==1.4.1
 - DJANGO_VERSION==1.4
install:
 - pip install -q Django=$DJANGO_VERSION
 - python JTTools.py -q run
 - python JTToolsInstaller.py -q run

